#!/usr/bin/env bash

#
# These aliases must be sources *AFTER* `shell/aliases`
#

# Core commands
# Requires 'coreutils': brew install coreutils
alias dircolors='gdircolors'
alias tar='gtar'
alias ls='gls -hFX --color=auto --group-directories-first'
alias chown='gchown --preserve-root'
alias chmod='gchmod --preserve-root'
alias chgrp='gchgrp --preserve-root'
alias readlink='greadlink'

# Processes
alias sys='launchctl'
unalias open

# Brew
alias brewupg='brew update && brew upgrade && brew upgrade --cask && brew cleanup'

# Shortcut because it is so hard to type '~' in Mac :/
export h="$HOME"
