#!/usr/bin/env bash

#
# These aliases must be sources *AFTER* `shell/aliases`
#

# Core commands
# Requires 'coreutils': brew install coreutils
alias tar='gtar'
alias ls='gls -hFX --color=auto --group-directories-first'

# Processes
alias sys='launchctl'

# Brew
alias brewupg='brew update && brew upgrade && brew cask upgrade && brew cleanup'

