#!/usr/bin/env bash

#
# These aliases must be sources *AFTER* `shell/aliases`
#

# Core commands
# Requires 'coreutils': brew install coreutils
alias tar='gtar'
alias ls='gls -hFX --color=auto --group-directories-first'
alias chown='gchown --preserve-root'
alias chmod='gchmod --preserve-root'
alias chgrp='gchgrp --preserve-root'

# Processes
alias sys='launchctl'

# Brew
alias brewupg='brew update && brew upgrade && brew cask upgrade && brew cleanup'

