#!/usr/bin/env bash

# Improved commands
alias top='htop'
alias cat='bat --paging=never'
alias less='bat'
alias more='bat'
#alias ps='procs'
#alias du='dust'

# Aliases
alias diff='colordiff' # requires colordiff package
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias open='xdg-open'
alias isodate='date +"%Y-%m-%dT%H:%M:%S"'

# modified commands
alias df='df -h'
alias du='du -c -h'
alias mkdir='mkdir -p -v'
alias ping='ping -c 5'
alias sudo='sudo -E'
alias free='free -m'

# new commands
alias da='date "+%A, %B %d, %Y [%T]"'
alias du1='du --max-depth=1'
alias h='history'
alias hs='h | grep $1' # requires an argument
alias hist='hs'        # requires an argument
alias openports='netstat --all --numeric --programs --inet'
alias pg='ps -Af | grep $1' # requires an argument

alias backup='rsync -a --delete'

# Git Bash fix (alias doesn't work)
#unalias hs
#hs () { h|grep $1; }

# privileged access
if [ $UID -ne 0 ]; then
  alias sudo='sudo '
  alias scat='sudo cat'
  alias svim='sudo vim'
  alias root='sudo su'
  alias reboot='sudo reboot'
  alias halt='sudo halt'
fi

# cd
alias back='cd "$OLDPWD"'
alias ..='cd ..'
alias ...='cd ../..'

# ls
alias ls='lsd -hF --color=auto --group-directories-first'
alias lr='ls -R' # recursive ls
alias ll='ls -l'
alias la='ll -A'
alias lx='ll -BX' # sort by extension
alias lz='ll -rS' # sort by size
alias lt='ll -rt' # sort by date
alias lm='la | more'
alias l='ls -AF'

# safety features
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

alias f='find .'
alias fn='find . -name'
alias fbak='sudo find / -name "*.bak" -or -name "*~"'

# Editors
alias vi='nvim'
alias vim='nvim'
alias hx='helix'

# Build systems
alias gw='./gradlew'
alias gwatch='gw -t'
alias gcb='gw clean build'
alias mw='./mvnw'
alias mci='mw clean install'
alias npr='npm run'

# Processes
alias sys='sudo systemctl'
alias sy='sys status'
alias syup='sys start'
alias sydown='sys stop'
alias syrestart='sys restart'
