#!/usr/bin/env sh

# SSH
alias tunnel='ssh -fNL'
alias lstunnel='ps -ef|grep "ssh -fNL"'

alias ssha='eval "$(ssh-agent -s)"'
alias kc='eval $(keychain --eval --quiet)'

kssh () {
    /usr/bin/ssh $@
    konsoleprofile colors=DarkPastels &>/dev/null
}

alias ssh=kssh
