#!/usr/bin/env sh

p12pem() {
  openssl pkcs12 -in ${1}.p12 -out ${1}.crt -clcerts -nokeys
  openssl pkcs12 -in ${1}.p12 -out ${1}.key -nocerts -nodes
}

jksp12() {
  keytool -importkeystore \
    -srckeystore ${1}.jks \
    -destkeystore ${1}.p12 \
    -deststoretype PKCS12 \
    -srcalias ${2:-client_priv} \
    -deststorepass ${3:-apisdksecret} \
    -destkeypass ${3:-apisdksecret}
}

https() {
  curl -vv -k --cert ${1}.crt --key ${1}.key ${2}
}
