#!/bin/sh

# Example: rgita remote \;
alias rgita='find . -type d -name .git -execdir git'

# Example: rgit remote -vv
rgit() {
  rgita "$@" \;
}

# Example: GIT_BASE="git@github.com:" clone hexagonkt/todokt
clone() {
    PROJECT_REPOSITORY=$1

    git clone "$GIT_BASE/${PROJECT_REPOSITORY}.git" "${PROJECT_REPOSITORY}"
}
