#!/usr/bin/env bash

# Define the Pacman wrapper (pacman, yay, etc.) to be used
alias pac='pacman'

alias pacupg='pac -Syu && paccache -rk 2' # Synchronize with repositories and clean cache
alias pacprune='pacrm $(pac -Qtdq)'     # Delete not required (orphan) packages
alias pacin='pac -S'     # Install specific package(s) from the repositories
alias pacinf='pac -Up'   # Install specific package not from the repositories but from a file
alias pacrm='pac -Rns'   # Remove specified package(s), configuration(s) and unneeded dependencies
alias pacrep='pac -Si'   # Display information about a given package in the repositories
alias pacreps='pac -Ss'  # Search for package(s) in the repositories
alias pacloc='pac -Qi'   # Display information about a given package in the local database
alias paclocs='pac -Qs'  # Search for package(s) in the local database
alias pacls='pac -Ql'    # Display the file list of a given package in the local database

