set nocompatible

source $VIMRUNTIME/mswin.vim

behave mswin

set guitablabel=%N\ %f
set number
set ignorecase
set ts=4
set sts=4
set sw=4
set et
set si
set nowrap
set fcs=vert:\ ,fold:-
set ed

map <CR> i<CR><ESC>
map <Space> i <ESC>l
map <S-Space> i
imap <S-Space> <ESC>
map <F12> <C-w>s
map <S-F12> <C-w>v
map <C-F12> <C-w>c
map <M-F12> i

map <F5> @a
map <F6> @b
map <F7> @c
map <F8> @d

:syn on
