#!/usr/bin/env bash

alias mk='minikube'
alias mkenv='eval $(mk docker-env)'
alias mkrm='mk stop ; mk delete --all'
alias mkinfo='mk config view && mk addons list && mk status && mk ip ; mk service list || true'

mknew() {

  # Setup
  mk config set driver docker
  mk config set cpus 2
  mk config set memory 4096
  mk config set insecure-registry "10.0.0.0/8"
  mk config set kubernetes-version latest

  # Start
  mk start
  mk addons enable metrics-server
  mk addons enable ingress
  mk addons enable ingress-dns
  mk addons enable dashboard

  mkinfo
}

alias kb='kubectl'
alias kbg='kb get'
alias kba='kb apply'
alias kbcu='kb config use'
