#!/usr/bin/env bash

alias mk='minikube'
alias mkrm='mk delete --all --purge'
alias mkinfo='mk config view && mk addons list && mk status && mk ip ; mk service list || true'

mknew() {

  # Setup
  mk config set driver docker
  mk config set cpus 2
  mk config set memory 4096
  mk config set insecure-registry "10.0.0.0/8"
  mk config set kubernetes-version latest

  # Start
  mk start
  mk addons enable metrics-server
  mk addons enable ingress
  mk addons enable ingress-dns
  mk addons enable dashboard
  mk addons enable registry

  mkinfo
}

alias kb='kubectl'
alias kbg='kb get'
alias kba='kb apply'
alias kbcu='kb config use'

