#!/usr/bin/env sh

alias vg='vagrant'
alias vgst='vg status'
alias vggst='vg global-status'
alias vgup='vg up'
alias vghalt='vg halt'
alias vgrm='vg destroy -f'
alias vgsh='vg ssh'
alias vgrebuild='vgrm && vgup'
