
if !has('nvim')
  set nocompatible
  source $VIMRUNTIME/mswin.vim
  behave mswin
  set viminfo+=n~/.vim/viminfo
endif

set nobackup
set nowritebackup
set noswapfile

set guitablabel=%N\ %f
set clipboard^=unnamed,unnamedplus
set guioptions=rgmtehb
set number
set ignorecase
set bdir=/tmp,~/tmp,.
set ts=4
set sts=4
set sw=4
set et
set si
set nowrap
set cursorline
set cursorcolumn
set fcs=vert:\ ,fold:-
set so=999
set mouse=a

map <CR> i<CR><ESC>
"map <Space> i <ESC>l

map <F5> @a
map <F6> @b
map <F7> @c
map <F8> @d

autocmd InsertEnter * :set norelativenumber
autocmd InsertLeave * :set relativenumber

"colorscheme desert
"syntax on

set encoding=utf8

" https://medium.com/geekculture/neovim-configuration-for-beginners-b2116dbbde84
set showmatch                " show matching 
set mouse=v                  " middle-click paste with 
set hlsearch                 " highlight search 
set incsearch                " incremental search
set tabstop=4                " number of columns occupied by a tab 
set softtabstop=4            " see multiple spaces as tabstops so <BS> does the right thing
set expandtab                " converts tabs to white space
set shiftwidth=4             " width for autoindents
set autoindent               " indent a new line the same amount as the line just typed
set wildmode=longest,list    " get bash-like tab completions
set textwidth=100
set colorcolumn=+1
filetype plugin indent on    " allow auto-indenting depending on file type
filetype plugin on
set ttyfast                  " Speed up scrolling in Vim
"set spell                  " enable spell check (may need to download language package)
"set backupdir=~/.cache/vim " Directory to store backup files.

"highlight ColorColumn ctermbg=8 guibg=DarkCyan
highlight CursorLine cterm=NONE ctermbg=Black guibg=Black
highlight CursorColumn cterm=NONE ctermbg=Black guibg=Black

"nnoremap <expr> p '"0p'
"nnoremap <expr> P '"0P'
"xnoremap <expr> p '"0p'
"xnoremap <expr> P '"0P'

