#!/usr/bin/env bash

# SSH
alias tunnel='ssh -fNL'
alias lstunnel='ps -ef|grep "ssh -fNL"'

alias ssha='eval "$(ssh-agent -s)"'

kssh () {
    /usr/bin/ssh $@
    konsoleprofile colors=DarkPastels
}

alias ssh=kssh

